---
load: POSTWORLD
main: LuckyBlock\Main
name: LuckyBlock
api: 2.0.0
author: georgianYT
version: 3.1.0
website: "https://github.com/georgianYT/LuckyBlock"
permissions:
  luckyblock:
    default: false
    description: "Allows using everything LuckyBlock has"
    children:
      luckyblock.command:
        default: op
        description: "Allows using /luckyblock command"
      luckyblock.use:
        default: true
        description: "Allows the player to use the plugin"
